apiVersion: v1
kind: Service
metadata:
  name: undertow-baseline
  labels:
    app: undertow-baseline
    framework: undertow
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  sessionAffinity: None
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: undertow-baseline
---
apiVersion: v1
kind: Service
metadata:
  name: undertow-baseline-headless
  labels:
    app: undertow-baseline
    framework: undertow
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8088
    targetPort: http
    protocol: TCP
  selector:
    app: undertow-baseline
