apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: undertow-baseline-metrics
  labels:
    app: undertow-baseline
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: undertow-baseline
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    scheme: http
    scrapeTimeout: 10s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_label_version]
      targetLabel: version
